Migration data
ikbentimkramer/cdphmd pull request #68
Opened 2020-12-15 22:52 UTC by Augustin4762

2020-12-16 10:04 UTC, Augustin4762 commented
Oh, the conflict with the get_data file is due to the fact that the branch migration was created before the recent update of the get_data function. If you could please make the necessary adjustments into this function.

2020-12-16 11:02 UTC, ikbentimkramer requested changes
Please run `devtools::check()` and resolve all errors, warnings and notes that it brings up. Will review again when that has been done.

2021-01-05 10:35 UTC, ikbentimkramer commented on tests/testthat/test-map_migration.R
> +test_map_migration <- function(df) {
This is not a test_that function, neither does it run some kind of test. Why is this in the tests folder and called test-map_migration?

2021-01-06 09:56 UTC, Augustin4762 commented
Could you please check why is there a conflict with the get_data function? I think I had this issue before the break and couldn't figure it out.

2021-01-06 10:09 UTC, ikbentimkramer approved these changes

2021-01-06 10:10 UTC, merged